language: python
python: "2.7"
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg -v 1.6.3
  - bin/buildout -c travis.cfg buildout:develop= buildout:auto-checkout= install download install 
  - bin/buildout -N -t 3 -c travis.cfg
script: 
  - bin/test
